from lettrecommandetest import lettreCommandeTest, notify_prestataire_save_Test
from ouverturerdvtest import ouvertureRdvTest
from sitetest import siteTest
from prestatairetest import prestataireTest
from chargeinsertiontest import chargeInsertionTest
from cloturetest import clotureTest
from csvViewTest import privateMethodTest, lcEncoursTest
from periodTest import periodTest
from querysetValidatortest import onePopulated_QuerySetTest, oneNotEnAttente_QuerySetTest, oneAbandonnee_QuerySetTest, oneEntreEnPresta_QuerySetTest, oneCloture_QuerySetTest
from rdvViewTest import emptyRdvTest, nonEmptyRdvTest
from bilanViewTest import persoAllEvents1Test, persoAllEvents2Test, persoAllEvents3Test
from stattest import StatResultTest, LCStatCalcTest, SiteCalcStatTest, SiteCalcFreinTest, FreinResultTest, LCFreinResultTest, LCFreinCalcTest
from feriestest import FeriesPaquesTest, IntervalleTest


